### ISSUE TITLE
Site Specific Thrivecart issue

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms-rest#233]
### Reproduction Steps

+ HS-171389
+ Credentials all provided in ticket
+ Log into LifterLMS Site -> Create new Rest API read/write credentials
+ Log into ThriveCart->(click on your profile logo)->Settings->Integrations->LifterLMS
+ Edit site syncing options
+ Add user's site and new rest api credentials
+ attempt to save

### Expected Behavior

+ It saves normally with the trial site, however user's site can't be authenticated
+ There is apparently a 500 error that I'm working on getting more information on
+ I'm still trying to find out if there's basic authentication allowed 
+ This all supposedly became an issue after 5.1 but again, our trial sites work just fine. 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
I'm working on getting this

```

### System Information

<details>
<summary>System Report</summary>
  
```
<!-- Paste your System Report below this line -->
Possible Issues:
The following may be contributing to your issue or causing errors on your site:
+ Your theme, Divi, does not declare support for LifterLMS. If you're encountering issues with how LifterLMS content looks on your site, consider asking your theme developers to add LifterLMS support to your theme. See our theme compatibility tutorials for more information.
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/hiveaccess/
Version: 5.8
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Course Catalog (#52781) [[removed]/course-catalog/]
Page On Front: Home Page (#53627) [[removed]/]
Permalink Structure: /%category%/%postname%/
Show On Front: page
Wp Cron: No


Settings
-------------------------------------------

Version: 5.1.0
Db Version: 5.1.0
Course Catalog: Courses (#50547) [[removed]/courses/]
Membership Catalog: Membership Catalog (#52604) [[removed]/membership-catalog/]
Student Dashboard: Dashboard (#50545) [[removed]/dashboard/]
Checkout Page: Registration Page (#50549) [[removed]/checkout/]
Course Catalog Per Page: 48
Course Catalog Sorting: date,DESC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: medium
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: optional
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: optional
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image: 50931
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 16384
Php Max Upload Size: 2 GB
Php Memory Limit: 2048M
Php Post Max Size: 1536M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 600
Php Version: 7.3.29
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36


Theme
-------------------------------------------

Name: Divi
Version: 4.9.10
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template:
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Bloom: 1.3.12
Classic Editor: 1.6.2
Duplicate Page: 4.4
Header Footer Code Manager: 1.1.10
LifterLMS: 5.1.0
LifterLMS Customizations: 1.0.0
LifterLMS Labs: 1.6.0
Monarch Plugin: 1.4.14
My Custom Functions: 4.49
Nav Menu Roles: 2.0.1
Quick Featured Images: 13.5.7
Really Simple SSL: 5.0.3
Redirection: 5.1.2
SendWP: 1.0.3
Spreaker Shortcode: 1.8.0
Uncanny Automator: 3.0.5
Uncanny Automator Pro: 3.0.2
UpdraftPlus - Backup/Restore: 2.16.59.25
WordPress Version Info: 1.2.1
WP Fusion: 3.37.28
WP Rollback: 1.7.1
WPS Hide Login: 1.8.5
Yoast SEO Premium: 15.7


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------
```

</details>

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 

We need logs to proceed. A 500 error could be caused by any number of things and us developers have no secret way of discovering the source of an error. The log files will tell us and that's what we need to proceed.

**Comment by nrherron92** [comment]
@thomasplevy It seems to be a conflict with Divi when he turns Divi off the issue goes away:

these are the error code: 

```[28-Jul-2021` 04:20:50 UTC] PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function ET_GB_Block_Layout::get_the_excerpt(), 1 passed in /chroot/home/abe7c2cc/jayabraham.com/html/wp-includes/class-wp-hook.php on line 303 and exactly 2 expected in /chroot/home/abe7c2cc/jayabraham.com/html/wp-content/themes/Divi/includes/builder/feature/gutenberg/blocks/Layout.php:207```


```Uncaught ArgumentCountError: Too few arguments to function ET_GB_Block_Layout::get_the_excerpt(), 1 passed in /chroot/home/abe7c2cc/jayabraham.com/html/wp-includes/class-wp-hook.php on line 303 and exactly 2 expected in /chroot/home/abe7c2cc/jayabraham.com/html/wp-content/themes/Divi/includes/builder/feature/gutenberg/blocks/Layout.php:207Stack trace: #0 /chroot/home/abe7c2cc/jayabraham.com/html/wp-includes/class-wp-hook.php(303): ET_GB_Block_Layout->get_the_excerpt('[et_pb_section ...') #2 /chroot/home/abe7c2cc/jayabraham.com/html/wp-content/plugins/lifterlms/includes/abstracts/abstract.llms.post.model.php(433): apply_filters('get_the_excerpt', '') #3 /chroot/home/abe7c2cc/jayabraham.com/html/wp-content/plugins/lifterlms/includes/abstracts/abstract.llms.post.model.php(175): LLMS_Post_Model->___get('excerpt')```

**Comment by eri-trabiccolo** [comment]
Thanks @nrherron92 !
https://github.com/gocodebox/lifterlms/pull/1719 fixes this @thomasplevy 
This means that our rest-api are currently not working with Divi 4.10.0... (latest release)
What the customer can do would be to rollback Divi...
